import type { Metadata } from "next";
import { Inter } from "next/font/google";

import {
  AnimationContextProvider,
  AppContainer,
  MyThemeProvider,
  StyledComponentsRegistry,
} from "@/helpers/lib";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hari - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MyThemeProvider>
            <AnimationContextProvider>
              <AppContainer>{children}</AppContainer>
            </AnimationContextProvider>
          </MyThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
