import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";

import { MyThemeProvider, StyledComponentsRegistry } from "@/helpers/lib";

const inter = League_Spartan({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledComponentsRegistry>
          <MyThemeProvider>{children}</MyThemeProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
